/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MCUX_CONFIG_H_
#define _MCUX_CONFIG_H_

#define DEMO_PANEL_ADAFRUIT_2_8 7
#define DEMO_PANEL_LCD_PAR_S035 8
#define CONFIG_MCUX_DEMO_PANEL_ADAFRUIT_2_8_SUPPORT 1
#define CONFIG_MCUX_DEMO_PANEL_LCD_PAR_S035_SUPPORT 1
#define CONFIG_CPU_CORTEX_M 1
#define CONFIG_FLASH_BASE_ADDRESS 0x08000000
#define CONFIG_FLASH_DEFAULT_APP_OFFSET 0x0
#define CONFIG_HAS_FLASH_LOAD_OFFSET 1
#define CONFIG_FLASH_LOAD_OFFSET 0x0
#define CONFIG_IMU_BUSY_POLL_COUNT 0
// #define CONFIG_FLASH_DRIVER_EXECUTES_FROM_RAM 0
// #define CONFIG_ENABLE_QUICKACCESS_SECTION_IN_XSPI_DRIVER 0
#define DEBUG_CONSOLE_SYNCHRONIZATION_MODE 0
// #define SERIAL_MANAGER_NON_BLOCKING_MODE 0
// #define CONFIG_FLASH_IPED 0
// #define CONFIG_STREAM_FLASH 0
// #define LIB_JPEG_USE_HW_ACCEL 0
// #define USE_PNGDEC_DRIVER 0
// #define CONFIG_BOOT_CUSTOM_DEVICE_SETUP 0
#define CONFIG_MPP_OS_FREERTOS 1
#define CONFIG_MPP_OS_NAME freertos
#define CONFIG_MPP_RC_TASK_STACK_SIZE 1200
#define CONFIG_MPP_PR_TASK_STACK_SIZE 1200
// #define MPU_SUPPORT 0
// #define USE_PERCEPIO_TRACELYZER 0

#endif /* _MCUX_CONFIG_H_ */
