#ifndef A2l_RPC_h
#define A2l_RPC_h

/*******************************************************************************
*
* Project             Clarinox SoftFrame
* File                A2l.RPC.h
* Description         Declares Clarinox Application Adaptation Layer related 
*                     types and macros For RPC 
*
* This software is copyrighted and contains proprietary information of 
* Clarinox Technologies Proprietary Limited. 
* Copying or reproduction without prior written approval is prohibited.
*
* All rights reserved. Copyright (c) 2001-2026 by Clarinox Technologies Pty. Ltd.
*
*******************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif


#define CLX_RPC_INDICATION_SCHEDULER_NAME             "ClarinoxRPC.Indication"
#define CLX_RPC_STACK_SCHEDULER_NAME                  "ClarinoxRPC.Stack"



CLX_DECLARE_C_OBJECT_RTTI(ClxRpcService);


typedef u2 ClxServiceID;


typedef boolean (*ClxRpcClientApplicationCallbackFunc) (ClxServiceID serviceID, u2 indicationID, const void* params, ClxError errorCode);

struct ClxA2lRpcBspInterface;

/**
This context ID is reserved for internal use and should not be used by the application.
*/
#define CLX_RPC_RESERVED_CONTEXT_ID                                 0xFF

/**
This service ID is reserved for internal use and should not be used by the application.
*/
#define CLX_RPC_RESERVED_SERVICE_ID                                 0xFFFF


/**
Refer to #clxRpcClientCreateCommandContext function.
*/
#define CLX_CREATE_COMMAND_CONTEXT_RPC_CLIENT_COMPLETE			    0x4005

/**
Refer to #clxSendVendorSpecificCommandRpcClient function.
*/
#define CLX_SEND_VENDOR_SPECIFIC_RPC_CLIENT_COMMAND_COMPLETE	    0x4006


/**
Used internally.
*/
#define CLX_CLOSE_RPC_SERVICE_COMPLETE                              0x4009


/* 
Reserved RPC ServiceIDs. These Service IDs must not be used by the applications: 
*/
#define CLARINOX_BLUE_STACK_SERVICE_ID                              0x1000      /* Fixed Service ID assigned to the ClarinoxBlue stack. Used internally. */
#define CLX_GAP_SERVICE_ID                                          0x1001      /* Service Id for Gap. This is a fixed id, which can be manually assigned to all Gap API's. */
#define CLX_GAP_BLE_SERVICE_ID                                      0x1002      /* Service Id for Ble. This is a fixed id, which can be manually assigned to all Gap Ble API's. */
#define CLARINOX_WLAN_STACK_SERVICE_ID                              0x1100      /* Fixed Service ID assigned to the ClarinoxWLAN stack. Used internally. */
#define WPA_SUPPLICANT_STACK_SERVICE_ID                             0x1101      /* Fixed Service ID assigned to the WPA Supplicant stack. Used internally. */


#define CLX_RPC_GENERIC_TEXT_MESSAGE_INDICATION_MAX_LENGTH	        128         /* Bytes */


/**
A generic user-defined indication which may be used to send text messages from the RPC server
to the RPC client. The argument of this indication is of type #ClxRpcGenericTextMessageIndication.
The argument contains a 32bit message ID which may be used to distinguish different indications.

IMPORTANT : The length of the text message is limited to #CLX_RPC_GENERIC_TEXT_MESSAGE_INDICATION_MAX_LENGTH bytes.

On the server side, an indication of this type is generated by a call to the function #clxA2lRpcServerSendGenericMessageIndication().
*/
#define CLX_RPC_GENERIC_TEXT_MESSAGE_INDICATION	                    0x8001


#define CLX_RPC_MIN_INCOMING_MTU                                    512  /* Bytes */
                                                                    
#define CLX_RPC_MIN_INCOMING_BUFFER_SIZE                            1024  /* Bytes */
                                                                    
#define CLX_RPC_MIN_OUTGOING_MTU                                    512  /* Bytes */
                                                                    
#define CLX_RPC_MIN_ACK_TIMEOUT_PERIOD                              500 /* ms */



/**
The structure of the argument if the indication #CLX_RPC_GENERIC_TEXT_MESSAGE_INDICATION.
*/
typedef struct ClxRpcGenericTextMessageIndicationStruct
{
    u4 messageID;
    s1 message[CLX_RPC_GENERIC_TEXT_MESSAGE_INDICATION_MAX_LENGTH + 1];
} ClxRpcGenericTextMessageIndication;


/**
Initializes an object of type ClxService for an RPC service.

\param[ in ] serviceID The RPC service ID.
\param[ in ] commandContextID The RPC command context ID.
\param[ out ] out The ClxService object to be initialized.
*/
void clxInitRpcServiceObject(_in_ u2 serviceID, _in_ u2 commandContextID, _out_ ClxService* out);


/**
Initializes The RPC manager engine on the RPC client side. The RPC client manager shall be initialized before
any other RPC-related API may be called.

A successful initialization of the RPC client manager does not imply a successful establishment of a RPC link to the RPC server. The application SHALL call #clxRpcStartClientLink() in order to start the RPC communication link to the RPC server. 

\param[ in ] bspInterface A pointer to the RPC BSP interface. An implementation of ClxA2lRpcBspInterface BSP interface defines how the RPC client
                          communicates with the RPC server (which may reside on the same or a separate device) over the RPC link. Please refer to the BSP documentation for more information about this interface.

\param[ in ] applicationCallbackFunc Callback function which is called when an indication is received from the RPC server. Unlike the standard (non-RPC) architecture, a callback function is defined
                                     for ALL RPC services. Therefore, when an indication which belongs to a RPC service is received from the RPC server, this callback function will be called. The service ID of the
                                     service to which the indication belongs is passed to the callback function.

\param[ in ] incomingMtu The Maximum Transmission Unit (MTU) size for incoming RPC packets transferred over the RPC link. This value determines the largest RPC command response/indication which may be received from the RPC server.
                         This value should match the outgoingMtu value of the RPC server.
                         This value cannot be less than CLX_RPC_MIN_INCOMING_MTU.

\param[ in ] outgoingMtu The Maximum Transmission Unit (MTU) size for outgoing RPC packets transferred over the RPC link. This value determines the largest RPC command request which may be sent to the RPC server.
                         This value should match the incomingMtu value of the RPC server.
                         This value cannot be less than CLX_RPC_MIN_OUTGOING_MTU.

\param[ in ] incomingBufferSize The size of the incoming buffer. This buffer shall be larger than incomingMTU.
                                This value cannot be less than CLX_RPC_MIN_INCOMING_BUFFER_SIZE.

\param[ in ] ackTimeoutPeriod The maximum time for which the RPC client waits to receive an ACK for the previously sent RPC request. The RPC server shall acknowledge reception of each RPC request packets using an ACK packet.
                              If this time elapses and an ACK is not received, then the RPC client may re-transmit the RPC request or deem the RPC link lost.
                              This value cannot be less than CLX_RPC_MIN_ACK_TIMEOUT_PERIOD.

\param[ in ] maxNumberOfRetries The number of times a RPC request packet is re-transmitted (due to failure to receive an ACK) before the RPC link is deemed lost.
                                A value of 0 means that a RPC packet is never re-transmitted.

\return CLX_SUCCESS if the initialization has been successful.
Any other value indicates an error.
*/
ClxResult clxRpcInitClientManager(struct ClxA2lRpcBspInterface* bspInterface, 
                                  ClxRpcClientApplicationCallbackFunc applicationCallbackFunc,                      
                                  u2 incomingMtu,
				                  u2 outgoingMtu,
				                  u4 incomingBufferSize,
				                  u2 ackTimeoutPeriod,
				                  u2 maxNumberOfRetries);

/**
Creates a RPC command context with a unique ID.

A RPC command context contains a virtual stack buffer, which is used to store the arguments of RPC requests, and a RPC request queue.

Each RPC request shall be sent using a RPC command context. Only one request may be pending on a RPC command context at any time. Therefore, if two or more
RPC requests need to be simultaneously processed by the RPC server, multiple command contexts shall be used.

It is the application responsibility to choose a unique numeric ID for the new command context.

The command context ID 0xFF is reserved for internal use and should not be used by the application.

The command context 0 is a special context which is automatically created when the RPC link is established. The command context 0 cannot be deleted or re-created.

NOTE : The command context 0 has a minimum context memory size (usually 128 bytes). If a bigger context memory is required (e.g. the request has a lot of input and/or output arguments), new
command contexts shall be explicitly created and used.

Blocking mode: This function will not return until the command is complete. The function return value indicates the 
               result of the command.

Non-blocking mode: This function will return immediately with the error code #CLX_ERROR_COMPLETION_PENDING.
                   When the command is complete, the call-back function will be called with an indication of type 
                   #CLX_CREATE_COMMAND_CONTEXT_RPC_CLIENT_COMPLETE.
                   This indication does not have any parameters.

\param[ in ] id The unique ID of the new RPC command context, as chosen by the application. Any value, except for 0, is valid. The ID shall not have been assigned to a precisely created command context.
\param[ in ] contextMemorySize The size of context memory. The context memory serves as a virtual stack buffer to store the input/output arguments of RPC requests. If the arguments of a RPC command is too
large to fit in the context memory, the context cannot be used to send that request to the RPC server, otherwise the command will fail with the error CLX_ERROR_A2L_RPC_NO_ENOUGH_CONTEXT_MEMORY.

\param[  in   ] block Indicates mode of operation:
                      TRUE: Blocking mode
                      FALSE: Non-blocking mode

\return In blocking mode, #CLX_SUCCESS if successful.
        In non-blocking mode, result of the actual operation will be passed to the callback function.

        Any result other than CLX_SUCCESS indicates an error.
*/
ClxResult clxRpcClientCreateCommandContext(u1 id, u4 contextMemorySize, boolean block);

/**
Establishes the RPC communication link between the RPC client and the RPC server. This function shall be called only on the client side and after the successful initialization of RPC client manager (using the function #clxRpcInitClientManager).

No communication between the RPC client and RPC server is possible until the RPC link is successfully established by a call to this function.

IMPORTANT : If implemented by the RPC BSP interface, this function will also try to reset the server device in order to make sure the RPC server device will be in correct state. Please refer to the BSP documentation for more information.

\return CLX_SUCCESS if successful.
        Any result other than CLX_SUCCESS indicates an error.
*/
ClxResult clxRpcStartClientLink(ClxConfigList* configParameters);

/**
Stops the RPC communication link between the RPC client and the RPC server.

IMPORTANT : After successful competition of this command, all currently initialized RPC command contexts and RPC services are deemed invalid. They all need to be re-initialized after the function #clxRpcStartClientLink() is called again
to re-establish the RPC link. This rule applies even if the RPC link fails inadvertently.

\return CLX_SUCCESS if successful.
        Any result other than CLX_SUCCESS indicates an error.
*/
ClxResult clxRpcStopClientLink(void);


/**
Terminates and destroys the RPC client manager.

\return CLX_SUCCESS if the command has been successful.
Any other value indicates an error.
*/
ClxResult clxRpcDestroyClientManager(void);


/**
Data Structure for the indication #CLX_SEND_VENDOR_SPECIFIC_RPC_CLIENT_COMMAND_COMPLETE
*/
typedef struct ClxSendVendorSpecificCommandCompleteStruct
{
    _inout_ ClxConfigList*  output;    /*!< Output arguments of the command, as a list of configuration parameters. This argument may be set to NULL */
} ClxSendVendorSpecificCommandComplete;


/**
Sends a vendor specific command to the RPC server. The command is not bound to any particular service.
The command is identified by a user-defined value called Vendor Command ID. The command may have input and/or output arguments.
Input and output arguments are sent and received as configuration parameters.
When the command is received by the RPC server, the BSP function which is pointed by clxHandleRpcServerVendorSpecificCommand function pointer will be called.
An implementation may dispatch the command to a correct command handler, using the Vendor Command ID.

Blocking mode: This function will not return until the command is complete. The function return value indicates the result of the command

Non-blocking mode: This function will return immediately with the error code CLX_ERROR_COMPLETION_PENDING.
                   When the command is complete, the call-back function will be called with an indication of type #CLX_SEND_VENDOR_SPECIFIC_RPC_CLIENT_COMMAND_COMPLETE.
                   The parameter of this indication is of type #ClxSendVendorSpecificCommandComplete.

\param[  in   ] serviceID        The ID of the remote service for which this command is destined.
\param[  in   ] contextID        The ID of the command context in which this command will be executed
\param[  in   ] vendorCommandID  The Vendor Command ID. This value may be used to identify the command
\param[ inout ] input            Input arguments of the command, as a list of configuration parameters. This argument may be set to NULL
\param[ inout ] output           Output arguments of the command, as a list of configuration parameters. This argument may be set to NULL
\param[  in   ] block            Indicates mode of operation:
                                 TRUE: Blocking mode
                                 FALSE: Non-blocking mode

\return ClxError Error code for the operation.

        - CLX_ERROR_COMPLETION_PENDING: operation will be completed asynchronously (only in non-blocking mode)
        - CLX_ERROR_COMMAND_CANCELLED: the handle was closed before the command has completed (only in blocking mode)
        - CLX_ERROR_COMMAND_NOT_COMPLETE: A previous same command has been issued which has not completed yet
        - CLX_ERROR_INVALID_HANDLE: invalid handle

*/
ClxResult clxSendVendorSpecificCommandRpcClient(_in_ ClxServiceID       serviceID,
                                                _in_ u1                 contextID,
                                                _in_ u2                 vendorCommandID,
                                                _inout_ ClxConfigList*  input,
                                                _inout_ ClxConfigList*  output,
                                                _in_ boolean            block);



extern ClxResult (*clxHandleRpcServerVendorSpecificCommand) (ClxHandle handle, u2 vendorCommandID, _inout_ ClxConfigList*  input, _inout_ ClxConfigList*  output);


/**
Closes the RPC Service. This is a blocking call by default. After closing the service, none of the operations on the service can be performed.

A service in closed state does any accept any command from the application.
Also, it will not send any indication to the application any longer.

IMPORTANT : When clxCloseRpcService() operation is progress, other threads are NOT allowed to call new API functions for this handle. This may result in undefined behaviour or a crash.
In multi-threaded designs, the application shall make sure this will not happen by setting a flag, or modifying the state of a state machine, 
in a manner that implies that that service is being closed, before calling clxCloseRpcService().

Blocking mode: This function will not return until the command is complete. The function return value indicates the result of the command

\param[  in   ] serviceID        The ID of the remote service which is to be closed.
\param[  in   ] contextID        The ID of the command context in which this command will be executed

\return CLX_SUCCESS                         The service was closed successfully. 

        CLX_ERROR_INVALID_HANDLE            The service specified is not valid (it is in a wrong state, or it is already closed)
        CLX_ERROR_HANDLE_COMMANDS_PENDING   The service does not support cancellation of pending commands, and one or more commands are pending at the time of calling this function.
        CLX_ERROR_INTERNAL_ERROR            Internal error occurred.
*/
ClxResult clxCloseRpcService(_in_ ClxServiceID  serviceID,
                             _in_ u1            contextID);


/**
Pings the stack to assure its responsiveness. 

An application may issue this command periodically to verify that the stack is responsive. Upon issuing this command for a stack, the application should also start a timer with a predefined timeout value.
If this command is not complete before the timer expires, the corresponding stack should be considered non-responsive and recovery procedures should be initiated.

NOTE : It is recommended that this command be issued in the non-blocking mode since this will verify responsiveness of both the stack thread and the indication handling thread. 

\param[ in ] serviceID          The stack base service ID. This value may be one of the following:
                                - CLARINOX_BLUE_STACK_SERVICE_ID : Ping ClarinoxBlue stack.
                                - CLARINOX_WLAN_STACK_SERVICE_ID : Ping ClarinoxWLAN stack.
                                - WPA_SUPPLICANT_STACK_SERVICE_ID : Ping WPA Supplicant stack.

\param[  in   ] contextID       The ID of the command context in which this command will be executed

\return #CLX_SUCCESS if successful.

        Other possible return values are:

        - #CLX_ERROR_COMPLETION_PENDING: Operation will be completed asynchronously (only in non-blocking mode)
        - #CLX_ERROR_COMMAND_NOT_SUPPORTED: If this command is not supported by the stack
*/
ClxResult clxPingStackRpcClient(_in_ ClxServiceID  serviceID,
                                _in_ u1            contextID);


/**
Sends raw binary data to the remote device over RPC link. This function may be called in either RPC client or RPC server device.

This function may be used to send unstructured (raw binary) data over the active RPC link.

data sent over a data channel is not bound to any service, and is not sent in the context of any command context. Therefore, it can be sent at any time (as long as the RPC link is active).
data is sent using the same RPC protocol (e.g. each data RPC frame is required to be ACKed). Therefore, the RPC configuration parameters ackTimeoutPeriod and maxNumberOfRetries apply
to RPC data channel frames as well.

Up to 256 data channels are available.

NOTE : There is no need to register a channel before being able to send data over it. However, the channel is required to be registered in order for the application to receive data from it. 
Refer to documentation of #clxRegisterRpcDataChannel for more information.

Non-contiguous data may be passed to this function, in the form of a linked list of one or more ClxDataSegment objects. 

If the entire data cannot fit in a single RPC frame, it will be fragmented into two or more RPC frames.

\param[ in ] channelID The ID of the data channel over which the data will be sent. May be 0 to 255.
\param[ in ] dataSegments A linked list of one or more objects of type dataSegments. Each segment object holds information about a contiguous segment of the data.

\return If an error occurs, and the delivery of the data has failed, the relevant error code will be returned.
If the data is successfully delivered to the remote device, the return value will be the same as the value returned by the RX handler function registered for the channel on the remote device.
*/
ClxResult clxSendDataToRpcDataChannel(_in_ u1 channelID, 
                                      _in_ ClxDataSegment* dataSegments);



/**
Interface for RPC Data Channel. The implemented interface is passed to the API function #clxRegisterRpcDataChannel to be registered.
The interface has only one method (rxDataReceived) which is mandatory to implement.
*/
typedef struct ClxRpcDataChannelStruct
{
    /**
    Called when a RPC data channel frame is received on the registered channel from the remote device.
    This function MUST be implemented.

    NOTE : This function is called in the context of the RPC (Client or Server) Manager thread. In order to avoid blocking the RPC Manager for a long time, the implementation of this function MUST
           return as soon as possible. If it would take a long time to process the received data, an implementation must make a copy of the data in a different buffer and process it in a different context.

    IMPORTANT : The implementation of this function MUST NOT call any RPC-related functions as this may result in a deadlock or unknown behaviour. 

    \param[ in ] this_ Pointer to the data channel object to which this method belongs.
    \param[ in ] channelID The of the channel over which the data channel frame has been. This argument may be useful if the same function is registered for two or more channels.
    \param[ in ] data The binary data received from the remote device. The data will be removed as soon as this function returns. If an implementation requires to keep hold of the data after
                      this function returns, it needs to copy the data in an implementation-specific buffer.
    \param[ in ] dataLength The length of the data received.
    */
    void (*rxDataReceived) (struct ClxRpcDataChannelStruct* this_, u2 channelID, const u1* data, u2 dataLength);
} ClxRpcDataChannel;


/**
Registers a RPC Data Channel with the RPC Client or Server manager. This function may be called in either RPC client or RPC server device.

An RPC data channel must be registered before any data may be received over it. If an RPC data channel frame is received for a channel which is not registered, the received frame is discarded.

\param[ in ] channelID The ID of the channel to be registered with the RPC Client or Server manager.
\param[ in ] channel The caller-allocated object of type ClxRpcDataChannel which represents the registered channel.
                     IMPORTANT : If the method rxDataReceived of the channel object has not been implemented, a BLACKBOX will occur. 

\return CLX_SUCCESS if the channel is successfully registered with the RPC manager. The method rxDataReceived of the channel object will not be called every time a data channel frame is received over this channel.
        CLX_ERROR_INVALID_COMMAND_ARGUMENT if the argument channel is NULL.
        CLX_ERROR_INVALID_REQUEST if the channel with the provided channelID is already registered with the RPC manager.
*/
ClxResult clxRegisterRpcDataChannel(_in_ u1 channelID,
                                    _in_ ClxRpcDataChannel* channel);


/**
Unregisters a RPC data channel from the RPC Client or Server manager. This function may be called in either RPC client or RPC server device.
When this function returns successfully, the method rxDataReceived of the channel is guaranteed to be not running and will not ren in the future.

\param [in ] channelID The ID of the channel to unregister from the RPC manager.

\return if the channel is successfully unregistered, it will return the data channel implementation. Note that this object is owned by the caller and will NOT be automatically deleted by this function.
        NULL if a channel with the specified channel ID has not been registered.
*/
ClxRpcDataChannel* clxUnregisterRpcDataChannel(_in_ u1 channelID);




/**
Initializes The RPC manager engine on the RPC server side.

\param[ in ] bspInterface A pointer to the RPC BSP interface.

\param[ in ] incomingMtu The Maximum Transmission Unit (MTU) size for incoming RPC packets transferred over the RPC link. This value determines the largest RPC commands which may be received from the RPC client.
                         This value should match the outgoingMtu value of the RPC client.
                         This value cannot be less than CLX_RPC_MIN_INCOMING_MTU.

\param[ in ] outgoingMtu The Maximum Transmission Unit (MTU) size for outgoing RPC packets transferred over the RPC link. This value determines the largest RPC command response/indication which may be sent to the RPC client.
                         This value should match the incomingMtu value of the RPC client.
                         This value cannot be less than CLX_RPC_MIN_OUTGOING_MTU.

\param[ in ] incomingBufferSize The size of the incoming buffer. This buffer shall be larger than incomingMTU. A value of 4096 bytes or more is recommended.
                                This value cannot be less than CLX_RPC_MIN_INCOMING_BUFFER_SIZE.

\param[ in ] ackTimeoutPeriod The maximum time for which the RPC server waits to receive an ACK for the previously sent RPC response/indication. The RPC client shall acknowledge reception of each RPC packets using an ACK packet.
                              If this time elapses and an ACK is not received, then the RPC server may re-transmit the RPC packet or deem the RPC link lost.
                              This value cannot be less than CLX_RPC_MIN_ACK_TIMEOUT_PERIOD.

\param[ in ] maxNumberOfRetries The number of times a RPC request packet is re-transmitted (due to failure to receive an ACK) before the RPC link is deemed lost.
                                A value of 0 means that a RPC packet is never re-transmitted.

\return CLX_SUCCESS if the initialization has been successful.
Any other value indicates an error.
*/
ClxResult clxRpcInitServerManager(struct ClxA2lRpcBspInterface* bspInterface,
                                  u2 incomingMtu,
			                      u2 outgoingMtu,
			                      u4 incomingBufferSize,
			                      u2 ackTimeoutPeriod,
			                      u2 maxNumberOfRetries);

/**
Generates an indication of type CLX_RPC_GENERIC_TEXT_MESSAGE_INDICATION on the RPC sever side, and sends it to the RPC client.

NOTE : This function may be called ONLY in the RPC server.

\param[ in ] messageID A user-defined numeric value which identifies the message.
\param[ in ] message   The text message to send to the RPC client. If this message is longer than #CLX_RPC_GENERIC_TEXT_MESSAGE_INDICATION_MAX_LENGTH bytes, it will be truncated.
*/
void clxA2lRpcServerSendGenericMessageIndication(u4 messageID, const s1* message);





#ifdef __cplusplus
}
#endif


#endif // A2l_RPC_h

/******************************************************************************/
/* 1. MISRA C 2004 RULE VIOLATION:                                            */
/* Message       : Identifiers (internal and external) shall not rely on the  */
/*                 significance of more than 31 characters.                   */
/* Rule          : MISRA-C:2004 Rule 5.1                                      */
/* Justification : Improves clarity of macro definitions. The compiler used   */
/*                 supports symbols longer than 31 characters, hence no risks.*/
/******************************************************************************/


/******************************************************************************/ 
/* 1. MISRA C 2012 RULE VIOLATION:                                            */ 
/* Message       : A project should not contain unused type declarations. 	  */
/* Rule          : MISRA-C:2012 Rule 2.3                                      */ 
/* Justification : Unused type declarations are to be used in user 		      */
/* 				   applications.      										  */
/******************************************************************************/

/******************************************************************************/ 
/* 1. MISRA C 2012 RULE VIOLATION:                                            */ 
/* Message       : A project should not contain unused tag declarations. 	  */
/* Rule          : MISRA-C:2012 Rule 2.4                                      */ 
/* Justification : Tag declarations are available to be used in user		  */ 
/*				   applications.    										  */
/******************************************************************************/

/******************************************************************************/ 
/* 1. MISRA C 2012 RULE VIOLATION:                                            */ 
/* Message       : A project should not contain unused macro declarations. 	  */
/* Rule          : MISRA-C:2012 Rule 2.5                                      */ 
/* Justification : Macro declarations are available to be used in user		  */ 
/*				   applications.											  */
/******************************************************************************/

