#ifndef __org_bluetooth_service_generic_telephone_bearer_service_h__
#define __org_bluetooth_service_generic_telephone_bearer_service_h__

/*******************************************************************************
*
* Project             Clarinox Reference Application
* File                org.bluetooth.service.generic_telephone_bearer_service.h
* Description         Declares definitions for the GATT service Generic Telephone Bearer Service
*
* This file contains proprietary information of
* Clarinox Technologies Proprietary Limited.
* Copying or reproduction without prior written approval is prohibited.
*
* All rights reserved. Copyright (c) 2001-2024 by Clarinox Technologies Pty. Ltd.
*
*******************************************************************************/



#ifdef __cplusplus
extern "C" {
#endif

/**
Generic Telephone Bearer Service GATT Service:
TBS is instantiated on devices that can make and/or receive phone calls. These devices include cell
phones; tablets; personal computers (PCs); laptops; wearable devices such as smart watches and smart
speakers/displays; and conference room equipment
*/
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_NAME    "Generic Telephone Bearer Service"
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_UUID    0x184C

/**
Bearer Provider Name Characteristic:

The UUID of this characteristic is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_PROVIDER_NAME_UUID.

The value of this characteristic is of type #ClxOrgBluetoothCharacteristicBearerProviderNameFields.

Local GATT Service:
The handle index of this characteristic in the local service is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_PROVIDER_NAME_HANDLE_INDEX.
The remote access permissions for this characteristic are defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_PROVIDER_NAME_PERMISSIONS.
*/
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_PROVIDER_NAME                 "Bearer Provider Name"
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_PROVIDER_NAME_HANDLE_INDEX    2
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_PROVIDER_NAME_PERMISSIONS     (CLX_GATT_ATTRIBUTE_PERMISSION_READABLE | CLX_GATT_ATTRIBUTE_PERMISSION_NOTIFIABLE | CLX_GATT_ATTRIBUTE_PERMISSION_ENCRYPTION_REQUIRED)
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_PROVIDER_NAME_STRUCT          struct ClxOrgBluetoothCharacteristicBearerProviderNameFields
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_PROVIDER_NAME_VALUE_TYPE      ClxOrgBluetoothCharacteristicBearerProviderNameFields_Type
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_PROVIDER_NAME_SIZE            ClxOrgBluetoothCharacteristicBearerProviderNameFields_Size
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_PROVIDER_NAME_UUID            0x2BB3

/**
Bearer UCI Characteristic:

The UUID of this characteristic is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_UCI_UUID.

The value of this characteristic is of type #ClxOrgBluetoothCharacteristicBearerUniformCallerIdentifierFields.

Local GATT Service:
The handle index of this characteristic in the local service is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_UCI_HANDLE_INDEX.
The remote access permissions for this characteristic are defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_UCI_PERMISSIONS.
*/
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_UCI                 "Bearer UCI"
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_UCI_HANDLE_INDEX    5
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_UCI_PERMISSIONS     (CLX_GATT_ATTRIBUTE_PERMISSION_READABLE | CLX_GATT_ATTRIBUTE_PERMISSION_ENCRYPTION_REQUIRED)
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_UCI_STRUCT          struct ClxOrgBluetoothCharacteristicBearerUniformCallerIdentifierFields
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_UCI_VALUE_TYPE      ClxOrgBluetoothCharacteristicBearerUniformCallerIdentifierFields_Type
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_UCI_SIZE            ClxOrgBluetoothCharacteristicBearerUniformCallerIdentifierFields_Size
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_UCI_UUID            0x2BB4

/**
Bearer Technology Characteristic:

The UUID of this characteristic is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_TECHNOLOGY_UUID.

The value of this characteristic is of type #ClxOrgBluetoothCharacteristicBearerTechnologyFields.

Local GATT Service:
The handle index of this characteristic in the local service is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_TECHNOLOGY_HANDLE_INDEX.
The remote access permissions for this characteristic are defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_TECHNOLOGY_PERMISSIONS.
*/
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_TECHNOLOGY                 "Bearer Technology"
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_TECHNOLOGY_HANDLE_INDEX    7
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_TECHNOLOGY_PERMISSIONS     (CLX_GATT_ATTRIBUTE_PERMISSION_READABLE | CLX_GATT_ATTRIBUTE_PERMISSION_NOTIFIABLE | CLX_GATT_ATTRIBUTE_PERMISSION_ENCRYPTION_REQUIRED)
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_TECHNOLOGY_STRUCT          struct ClxOrgBluetoothCharacteristicBearerTechnologyFields
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_TECHNOLOGY_VALUE_TYPE      ClxOrgBluetoothCharacteristicBearerTechnologyFields_Type
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_TECHNOLOGY_SIZE            ClxOrgBluetoothCharacteristicBearerTechnologyFields_Size
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_TECHNOLOGY_UUID            0x2BB5

/**
Bearer URI Schemes Supported List Characteristic:

The UUID of this characteristic is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_URI_SCHEMES_SUPPORTED_LIST_UUID.

The value of this characteristic is of type #ClxOrgBluetoothCharacteristicBearerUriSchemesSupportedListFields.

Local GATT Service:
The handle index of this characteristic in the local service is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_URI_SCHEMES_SUPPORTED_LIST_HANDLE_INDEX.
The remote access permissions for this characteristic are defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_URI_SCHEMES_SUPPORTED_LIST_PERMISSIONS.
*/
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_URI_SCHEMES_SUPPORTED_LIST                 "Bearer URI Schemes Supported List"
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_URI_SCHEMES_SUPPORTED_LIST_HANDLE_INDEX    10
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_URI_SCHEMES_SUPPORTED_LIST_PERMISSIONS     (CLX_GATT_ATTRIBUTE_PERMISSION_READABLE | CLX_GATT_ATTRIBUTE_PERMISSION_ENCRYPTION_REQUIRED)
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_URI_SCHEMES_SUPPORTED_LIST_STRUCT          struct ClxOrgBluetoothCharacteristicBearerUriSchemesSupportedListFields
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_URI_SCHEMES_SUPPORTED_LIST_VALUE_TYPE      ClxOrgBluetoothCharacteristicBearerUriSchemesSupportedListFields_Type
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_URI_SCHEMES_SUPPORTED_LIST_SIZE            ClxOrgBluetoothCharacteristicBearerUriSchemesSupportedListFields_Size
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_URI_SCHEMES_SUPPORTED_LIST_UUID            0x2BB6

/**
Bearer List Current Calls Characteristic:

The UUID of this characteristic is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_LIST_CURRENT_CALLS_UUID.

The value of this characteristic is of type #ClxOrgBluetoothCharacteristicBearerListCurrentCallsFields.

Local GATT Service:
The handle index of this characteristic in the local service is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_LIST_CURRENT_CALLS_HANDLE_INDEX.
The remote access permissions for this characteristic are defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_LIST_CURRENT_CALLS_PERMISSIONS.
*/
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_LIST_CURRENT_CALLS                 "Bearer List Current Calls"
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_LIST_CURRENT_CALLS_HANDLE_INDEX    12
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_LIST_CURRENT_CALLS_PERMISSIONS     (CLX_GATT_ATTRIBUTE_PERMISSION_READABLE | CLX_GATT_ATTRIBUTE_PERMISSION_NOTIFIABLE | CLX_GATT_ATTRIBUTE_PERMISSION_ENCRYPTION_REQUIRED)
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_LIST_CURRENT_CALLS_STRUCT          struct ClxOrgBluetoothCharacteristicBearerListCurrentCallsFields
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_LIST_CURRENT_CALLS_VALUE_TYPE      ClxOrgBluetoothCharacteristicBearerListCurrentCallsFields_Type
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_LIST_CURRENT_CALLS_SIZE            ClxOrgBluetoothCharacteristicBearerListCurrentCallsFields_Size
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_BEARER_LIST_CURRENT_CALLS_UUID            0x2BB8

/**
Content Control ID Characteristic:

The UUID of this characteristic is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CONTENT_CONTROL_ID_UUID.

The value of this characteristic is of type #ClxOrgBluetoothCharacteristicContentControlIdFields.

Local GATT Service:
The handle index of this characteristic in the local service is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CONTENT_CONTROL_ID_HANDLE_INDEX.
The remote access permissions for this characteristic are defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CONTENT_CONTROL_ID_PERMISSIONS.
*/
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CONTENT_CONTROL_ID                 "Content Control ID"
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CONTENT_CONTROL_ID_HANDLE_INDEX    15
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CONTENT_CONTROL_ID_PERMISSIONS     (CLX_GATT_ATTRIBUTE_PERMISSION_READABLE | CLX_GATT_ATTRIBUTE_PERMISSION_ENCRYPTION_REQUIRED)
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CONTENT_CONTROL_ID_STRUCT          struct ClxOrgBluetoothCharacteristicContentControlIdFields
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CONTENT_CONTROL_ID_VALUE_TYPE      ClxOrgBluetoothCharacteristicContentControlIdFields_Type
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CONTENT_CONTROL_ID_SIZE            ClxOrgBluetoothCharacteristicContentControlIdFields_Size
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CONTENT_CONTROL_ID_UUID            0x2BBA

/**
Status Flags Characteristic:

The UUID of this characteristic is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_STATUS_FLAGS_UUID.

The value of this characteristic is of type #ClxOrgBluetoothCharacteristicStatusFlagsFields.

Local GATT Service:
The handle index of this characteristic in the local service is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_STATUS_FLAGS_HANDLE_INDEX.
The remote access permissions for this characteristic are defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_STATUS_FLAGS_PERMISSIONS.
*/
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_STATUS_FLAGS                 "Status Flags"
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_STATUS_FLAGS_HANDLE_INDEX    17
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_STATUS_FLAGS_PERMISSIONS     (CLX_GATT_ATTRIBUTE_PERMISSION_READABLE | CLX_GATT_ATTRIBUTE_PERMISSION_NOTIFIABLE | CLX_GATT_ATTRIBUTE_PERMISSION_ENCRYPTION_REQUIRED)
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_STATUS_FLAGS_STRUCT          struct ClxOrgBluetoothCharacteristicStatusFlagsFields
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_STATUS_FLAGS_VALUE_TYPE      ClxOrgBluetoothCharacteristicStatusFlagsFields_Type
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_STATUS_FLAGS_SIZE            ClxOrgBluetoothCharacteristicStatusFlagsFields_Size
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_STATUS_FLAGS_UUID            0x2BBB

/**
Call State Characteristic:

The UUID of this characteristic is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_STATE_UUID.

The value of this characteristic is of type #ClxOrgBluetoothCharacteristicCallStateFields.

Local GATT Service:
The handle index of this characteristic in the local service is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_STATE_HANDLE_INDEX.
The remote access permissions for this characteristic are defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_STATE_PERMISSIONS.
*/
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_STATE                 "Call State"
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_STATE_HANDLE_INDEX    20
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_STATE_PERMISSIONS     (CLX_GATT_ATTRIBUTE_PERMISSION_READABLE | CLX_GATT_ATTRIBUTE_PERMISSION_NOTIFIABLE | CLX_GATT_ATTRIBUTE_PERMISSION_ENCRYPTION_REQUIRED)
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_STATE_STRUCT          struct ClxOrgBluetoothCharacteristicCallStateFields
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_STATE_VALUE_TYPE      ClxOrgBluetoothCharacteristicCallStateFields_Type
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_STATE_SIZE            ClxOrgBluetoothCharacteristicCallStateFields_Size
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_STATE_UUID            0x2BBD

/**
Call Control Point Characteristic:

The UUID of this characteristic is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_UUID.

The value of this characteristic is of type #ClxOrgBluetoothCharacteristicCallControlPointFields.

Local GATT Service:
The handle index of this characteristic in the local service is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_HANDLE_INDEX.
The remote access permissions for this characteristic are defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_PERMISSIONS.
*/
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT                 "Call Control Point"
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_HANDLE_INDEX    23
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_PERMISSIONS     (CLX_GATT_ATTRIBUTE_PERMISSION_WRITABLE | CLX_GATT_ATTRIBUTE_PERMISSION_WRITABLE_WITHOUT_RESPONSE | CLX_GATT_ATTRIBUTE_PERMISSION_NOTIFIABLE | CLX_GATT_ATTRIBUTE_PERMISSION_ENCRYPTION_REQUIRED)
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_STRUCT          struct ClxOrgBluetoothCharacteristicCallControlPointFields
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_VALUE_TYPE      ClxOrgBluetoothCharacteristicCallControlPointFields_Type
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_SIZE            ClxOrgBluetoothCharacteristicCallControlPointFields_Size
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_UUID            0x2BBE

/**
Call Control Point Optional Opcode Characteristic:

The UUID of this characteristic is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_OPTIONAL_OPCODE_UUID.

The value of this characteristic is of type #ClxOrgBluetoothCharacteristicCallControlPointOptionalOpcodeFields.

Local GATT Service:
The handle index of this characteristic in the local service is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_OPTIONAL_OPCODE_HANDLE_INDEX.
The remote access permissions for this characteristic are defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_OPTIONAL_OPCODE_PERMISSIONS.
*/
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_OPTIONAL_OPCODE                 "Call Control Point Optional Opcode"
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_OPTIONAL_OPCODE_HANDLE_INDEX    26
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_OPTIONAL_OPCODE_PERMISSIONS     (CLX_GATT_ATTRIBUTE_PERMISSION_READABLE | CLX_GATT_ATTRIBUTE_PERMISSION_ENCRYPTION_REQUIRED)
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_OPTIONAL_OPCODE_STRUCT          struct ClxOrgBluetoothCharacteristicCallControlPointOptionalOpcodeFields
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_OPTIONAL_OPCODE_VALUE_TYPE      ClxOrgBluetoothCharacteristicCallControlPointOptionalOpcodeFields_Type
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_OPTIONAL_OPCODE_SIZE            ClxOrgBluetoothCharacteristicCallControlPointOptionalOpcodeFields_Size
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_CALL_CONTROL_POINT_OPTIONAL_OPCODE_UUID            0x2BBF

/**
Termination Reason Characteristic:

The UUID of this characteristic is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_TERMINATION_REASON_UUID.

The value of this characteristic is of type #ClxOrgBluetoothCharacteristicTerminationReasonFields.

Local GATT Service:
The handle index of this characteristic in the local service is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_TERMINATION_REASON_HANDLE_INDEX.
The remote access permissions for this characteristic are defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_TERMINATION_REASON_PERMISSIONS.
*/
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_TERMINATION_REASON                 "Termination Reason"
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_TERMINATION_REASON_HANDLE_INDEX    28
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_TERMINATION_REASON_PERMISSIONS     (CLX_GATT_ATTRIBUTE_PERMISSION_NOTIFIABLE | CLX_GATT_ATTRIBUTE_PERMISSION_ENCRYPTION_REQUIRED)
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_TERMINATION_REASON_STRUCT          struct ClxOrgBluetoothCharacteristicTerminationReasonFields
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_TERMINATION_REASON_VALUE_TYPE      ClxOrgBluetoothCharacteristicTerminationReasonFields_Type
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_TERMINATION_REASON_SIZE            ClxOrgBluetoothCharacteristicTerminationReasonFields_Size
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_TERMINATION_REASON_UUID            0x2BC0

/**
Incoming Call Characteristic:

The UUID of this characteristic is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_INCOMING_CALL_UUID.

The value of this characteristic is of type #ClxOrgBluetoothCharacteristicIncomingCallFields.

Local GATT Service:
The handle index of this characteristic in the local service is defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_INCOMING_CALL_HANDLE_INDEX.
The remote access permissions for this characteristic are defined by #CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_INCOMING_CALL_PERMISSIONS.
*/
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_INCOMING_CALL                 "Incoming Call"
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_INCOMING_CALL_HANDLE_INDEX    31
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_INCOMING_CALL_PERMISSIONS     (CLX_GATT_ATTRIBUTE_PERMISSION_NOTIFIABLE | CLX_GATT_ATTRIBUTE_PERMISSION_ENCRYPTION_REQUIRED)
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_INCOMING_CALL_STRUCT          struct ClxOrgBluetoothCharacteristicIncomingCallFields
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_INCOMING_CALL_VALUE_TYPE      ClxOrgBluetoothCharacteristicIncomingCallFields_Type
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_INCOMING_CALL_SIZE            ClxOrgBluetoothCharacteristicIncomingCallFields_Size
#define CLX_GATT_SERVICE_GENERIC_TELEPHONE_BEARER_SERVICE_CHARACTERISTIC_INCOMING_CALL_UUID            0x2BC1

/**
Returns the interface to Generic Telephone Bearer Service GATT service.
The interface may be used to register one or more instances of this service in the local GATT server

\return The interface to Generic Telephone Bearer Service GATT service. The interface SHALL NOT be modified or removed
*/
extern const ClxBleGattServiceInterface* clxGetGenericTelephoneBearerServiceGattServiceInterface();


#ifdef __cplusplus
}
#endif

#endif // __org_bluetooth_service_generic_telephone_bearer_service_h__

