#ifndef WlanErrors_h
#define WlanErrors_h

/******************************************************************************
 *
 * Project             ClarinoxWLAN
 * File                WlanErrors.h
 * Description         Declares Clarinox WLAN common errors
 *
* This software is copyrighted and contains proprietary information of
* Clarinox Technologies Proprietary Limited.
* Copying or reproduction without prior written approval is prohibited.
*
* All rights reserved. Copyright (c) 2001-2026 by Clarinox Technologies Pty. Ltd.
*
*******************************************************************************/

#include "ClarinoxErrorCodes.h"

/** 
All errors are of type ClxResult. These error codes are positive numbers, so they can be used as both
internal errors, or API errors (the error codes which are reported to the API user).
Error codes 0x1000 through 0x1FFF may be used for ClarinoxWLAN.
*/

#define CLX_WLAN_ERROR_BASE												0x1000

#define CLX_WLAN_FAILED													(CLX_WLAN_ERROR_BASE + 01)
#define CLX_WLAN_TERMINATED												(CLX_WLAN_ERROR_BASE + 02)
#define CLX_WLAN_REQUEST_PENDING										CLX_ERROR_COMPLETION_PENDING
#define CLX_WLAN_ERROR_UNKNOWN_VIRTUAL_INTERFACE						(CLX_WLAN_ERROR_BASE + 04)
#define CLX_WLAN_ERROR_NOT_ENOUGH_RESOURCES								(CLX_WLAN_ERROR_BASE + 05)
#define CLX_WLAN_ERROR_INVALID_PARAMETERS								CLX_ERROR_INVALID_COMMAND_ARGUMENT
#define CLX_WLAN_ERROR_DRIVER_INIT_FAILED								(CLX_WLAN_ERROR_BASE + 07)
#define CLX_WLAN_ERROR_MULTIPLE_REQUESTS_NOT_ALLOWED					(CLX_WLAN_ERROR_BASE + 08)
#define CLX_WLAN_ERROR_HARD_RESET_FAILED								(CLX_WLAN_ERROR_BASE + 09)
#define CLX_WLAN_ERROR_SOFT_RESET_FAILED								(CLX_WLAN_ERROR_BASE + 10)
#define CLX_WLAN_ERROR_NO_FIRMWARE_FOUND								(CLX_WLAN_ERROR_BASE + 11)
#define CLX_WLAN_ERROR_BAD_FIRMWARE_FORMAT								(CLX_WLAN_ERROR_BASE + 12)
#define CLX_WLAN_ERROR_INSUFFICIENT_MEMORY								(CLX_WLAN_ERROR_BASE + 13)
#define CLX_WLAN_ERROR_PLATFORM_NOT_SUPPORTED							(CLX_WLAN_ERROR_BASE + 14)
#define CLX_WLAN_ERROR_NO_NVS_FOUND										(CLX_WLAN_ERROR_BASE + 15)
#define CLX_WLAN_ERROR_BAD_NVS_FORMAT									(CLX_WLAN_ERROR_BASE + 16)
#define CLX_WLAN_ERROR_CHIPSET_NOT_SUPPORTED							(CLX_WLAN_ERROR_BASE + 17)
#define CLX_WLAN_ERROR_BOOT_PROCESS_FAILED								(CLX_WLAN_ERROR_BASE + 18)
#define CLX_WLAN_ERROR_ANOTHER_COMMAND_PENDING							(CLX_WLAN_ERROR_BASE + 19)
#define CLX_WLAN_ERROR_USER_TIMEOUT_OCCURRED							CLX_ERROR_TIMEOUT_OCCURRED
#define CLX_WLAN_ERROR_SCAN_FAILED										(CLX_WLAN_ERROR_BASE + 21)
#define CLX_WLAN_ERROR_NOT_IMPLEMENTED									(CLX_WLAN_ERROR_BASE + 22)
#define CLX_WLAN_ERROR_BASIC_RATE_SET_NOT_SUPPORTED						(CLX_WLAN_ERROR_BASE + 23)
#define CLX_WLAN_ERROR_NOT_ENOUGH_MEMORY								CLX_SYSTEM_ENOMEM
#define CLX_WLAN_ERROR_SEGMENTED_RX_PDU_PENDING							(CLX_WLAN_ERROR_BASE + 25)
#define CLX_WLAN_ERROR_FRAME_PARSING_ERROR								(CLX_WLAN_ERROR_BASE + 26)
#define CLX_WLAN_ERROR_STACK_TERMINATING								(CLX_WLAN_ERROR_BASE + 27)
#define CLX_WLAN_ERROR_TOO_MANY_REQUESTS_PENDING						(CLX_WLAN_ERROR_BASE + 28)
#define CLX_WLAN_ERROR_AUTHENTICATION_FAILED							(CLX_WLAN_ERROR_BASE + 29)
#define CLX_WLAN_ERROR_ASSOCIATION_FAILED								(CLX_WLAN_ERROR_BASE + 30)
#define CLX_WLAN_ERROR_INTERFACE_IN_WRONG_STATE							(CLX_WLAN_ERROR_BASE + 31)
#define CLX_WLAN_ERROR_BSS_INFO_NOT_AVAILABLE							(CLX_WLAN_ERROR_BASE + 32)
#define CLX_WLAN_ERROR_NOT_SUPPORTED_BY_VIRTUAL_INTERFACE				(CLX_WLAN_ERROR_BASE + 33)
#define CLX_WLAN_ERROR_VIRTUAL_INTERFACE_TYPE_INCORRECT					(CLX_WLAN_ERROR_BASE + 34)
#define CLX_WLAN_ERROR_COMMAND_CANCELLED								(CLX_WLAN_ERROR_BASE + 35)
#define CLX_WLAN_ERROR_INTERFACE_NOT_STARTED							(CLX_WLAN_ERROR_BASE + 36)
#define CLX_WLAN_ERROR_NOT_SUPPORTED_BY_ROLE							(CLX_WLAN_ERROR_BASE + 37)
#define CLX_WLAN_ERROR_ACKNOWLEDGEMENT_FAILED							(CLX_WLAN_ERROR_BASE + 38)
#define CLX_WLAN_ERROR_HARDWARE_ERROR_OCCURRED							(CLX_WLAN_ERROR_BASE + 39)
#define CLX_WLAN_ERROR_PRE_ASSOC_AUTHENTICATION_NOT_SUPPORTED			(CLX_WLAN_ERROR_BASE + 40)
#define CLX_WLAN_ERROR_KEY_INSTALLATION_FAILED							(CLX_WLAN_ERROR_BASE + 41)
#define CLX_WLAN_ERROR_REQUESTED_ENC_NOT_SUPPORTED_BY_DRIVER			(CLX_WLAN_ERROR_BASE + 42)       /*!< Requested encryption protocol is not supported by the driver */
#define CLX_WLAN_ERROR_REQUESTED_AUTH_NOT_SUPPORTED_BY_DRIVER			(CLX_WLAN_ERROR_BASE + 43)       /*!< Requested authentication mechanism is not supported by the driver */
#define CLX_WLAN_ERROR_REQUESTED_ENC_NOT_SUPPORTED_BY_BSS				(CLX_WLAN_ERROR_BASE + 44)       /*!< Requested encryption protocol is not supported by the RemoteAccessPoint */
#define CLX_WLAN_ERROR_REQUESTED_AUTH_NOT_SUPPORTED_BY_BSS				(CLX_WLAN_ERROR_BASE + 45)       /*!< Requested authentication mechanism is not supported by the RemoteAccessPoint */
#define CLX_WLAN_ERROR_CONNECTION_TO_NETWORK_STACK_FAILED				(CLX_WLAN_ERROR_BASE + 46)
#define CLX_WLAN_ERROR_INTERFACE_STARTED								(CLX_WLAN_ERROR_BASE + 47)
#define CLX_WLAN_ERROR_ASSOCIATION_REQUESTED_BEFORE_AUTHENTICATION		(CLX_WLAN_ERROR_BASE + 48)
#define CLX_WLAN_ERROR_PRE_ASSOC_AUTHENTICATION_CHALLENGE_FAILED		(CLX_WLAN_ERROR_BASE + 49)
#define CLX_WLAN_ERROR_PRE_ASSOC_AUTHENTICATION_TIMEOUT					(CLX_WLAN_ERROR_BASE + 50)
#define CLX_WLAN_ERROR_REASSOCIATION_DENIED								(CLX_WLAN_ERROR_BASE + 51)
#define CLX_WLAN_ERROR_ASSOCIATION_DENIED_IEEE802_11b_CONFIG_MISMATCH	(CLX_WLAN_ERROR_BASE + 52)
#define CLX_WLAN_ERROR_ASSOCIATION_DENIED_IEEE802_11g_CONFIG_MISMATCH	(CLX_WLAN_ERROR_BASE + 53)
#define CLX_WLAN_ERROR_ASSOCIATION_DENIED_IEEE802_11h_CONFIG_MISMATCH	(CLX_WLAN_ERROR_BASE + 54)
#define CLX_WLAN_ERROR_ASSOCIATION_DENIED								(CLX_WLAN_ERROR_BASE + 55)
#define CLX_WLAN_ERROR_UNKNOWN_IEEE802_11_ERROR							(CLX_WLAN_ERROR_BASE + 56)
#define CLX_WLAN_ERROR_INVALID_PRE_ASSOC_AUTHENTICATION_ALGORITHM		(CLX_WLAN_ERROR_BASE + 57)
#define CLX_WLAN_ERROR_UNEXPECTED_SEQUENCE_NUMBER						(CLX_WLAN_ERROR_BASE + 58)
#define CLX_WLAN_ERROR_UNSPECIFIED_FAILURE								(CLX_WLAN_ERROR_BASE + 59)
#define CLX_WLAN_ERROR_4WAY_KEY_HANDSHAKE_TIMEOUT						(CLX_WLAN_ERROR_BASE + 60)
#define CLX_WLAN_ERROR_GROUPWISE_KEY_HANDSHAKE_TIMEOUT					(CLX_WLAN_ERROR_BASE + 61)
#define CLX_WLAN_ERROR_HANDSHAKE_INFO_MISMATCH							(CLX_WLAN_ERROR_BASE + 62)
#define CLX_WLAN_ERROR_INVALID_SECURITY_INFORMATION_ELEMENT				(CLX_WLAN_ERROR_BASE + 63)
#define CLX_WLAN_ERROR_INVALID_GROUPWISE_CIPHER							(CLX_WLAN_ERROR_BASE + 64)
#define CLX_WLAN_ERROR_INVALID_PAIRWISE_CIPHER							(CLX_WLAN_ERROR_BASE + 65)
#define CLX_WLAN_ERROR_INVALID_AUTHENTICATION_PROTOCOL					(CLX_WLAN_ERROR_BASE + 66)
#define CLX_WLAN_ERROR_UNSUPPORTED_RSN_IE_VERSION						(CLX_WLAN_ERROR_BASE + 67)
#define CLX_WLAN_ERROR_INVALID_CAPABILITIES_IN_RSN						(CLX_WLAN_ERROR_BASE + 68)
#define CLX_WLAN_ERROR_IEEE802_1X_AUTHENTICATION_FAILED					(CLX_WLAN_ERROR_BASE + 69)
#define CLX_WLAN_ERROR_DEAUTHENTICATED_STATION_LEFT_BSS					(CLX_WLAN_ERROR_BASE + 70)
#define CLX_WLAN_ERROR_DEASSOCIATED_STATION_LEFT_BSS					(CLX_WLAN_ERROR_BASE + 71)
#define CLX_WLAN_ERROR_STATION_INACTIVITY_TIMER_EXPIRED					(CLX_WLAN_ERROR_BASE + 72)
#define CLX_WLAN_ERROR_INCORRECT_FRAME_TYPE_FROM_UNAUTHENTICATED_STA	(CLX_WLAN_ERROR_BASE + 73)
#define CLX_WLAN_ERROR_INCORRECT_FRAME_TYPE_FROM_UNASSOCIATED_STA		(CLX_WLAN_ERROR_BASE + 74)
#define CLX_WLAN_ERROR_ROLE_NOT_STARTED									(CLX_WLAN_ERROR_BASE + 75)
#define CLX_WLAN_ERROR_ROLE_HAS_STARTED									(CLX_WLAN_ERROR_BASE + 76)
#define CLX_WLAN_ERROR_CONNECTION_ATTEMPT_TIMEOUT						(CLX_WLAN_ERROR_BASE + 77)
#define CLX_WLAN_ERROR_LINK_NOT_SECURE_FOR_GROUPKEY_TRANSFER			(CLX_WLAN_ERROR_BASE + 78)
#define CLX_WLAN_ERROR_HT_WITH_TKIP_ONLY_IS_ILLEGAL						(CLX_WLAN_ERROR_BASE + 79)
#define CLX_WLAN_ERROR_ILLEGAL_FREQUENCY_CHANNEL						(CLX_WLAN_ERROR_BASE + 80)
#define CLX_WLAN_ERROR_BSS_TYPE_DOES_NOT_MATCH_INTERFACE_TYPE			(CLX_WLAN_ERROR_BASE + 81)
#define CLX_WLAN_ERROR_EAP_SESSION_TERMINATED_SUCCESSFULLY				(CLX_WLAN_ERROR_BASE + 82)
#define CLX_WLAN_ERROR_EAP_SESSION_FAILED								(CLX_WLAN_ERROR_BASE + 83)
#define CLX_WLAN_ERROR_WPS_OOB_INTERFACE_READ_ERROR						(CLX_WLAN_ERROR_BASE + 84)
#define CLX_WLAN_ERROR_WPS_DECRYPTION_CRC_ERROR							(CLX_WLAN_ERROR_BASE + 85)
#define CLX_WLAN_ERROR_WPS_2_4_GHZ_CHANNEL_NOT_SUPPORTED				(CLX_WLAN_ERROR_BASE + 86)
#define CLX_WLAN_ERROR_WPS_5_GHZ_CHANNEL_NOT_SUPPORTED					(CLX_WLAN_ERROR_BASE + 87)
#define CLX_WLAN_ERROR_WPS_EXTERNAL_REGISTRAR_NOT_REACHABLE				(CLX_WLAN_ERROR_BASE + 88)
#define CLX_WLAN_ERROR_WPS_MULTIPLE_PBC_SESSION_DETECTED				(CLX_WLAN_ERROR_BASE + 89)
#define CLX_WLAN_ERROR_WPS_ROGUE_ACTIVITY_SUSPECTED						(CLX_WLAN_ERROR_BASE + 90)
#define CLX_WLAN_ERROR_WPS_DEVICE_BUSY									(CLX_WLAN_ERROR_BASE + 91)
#define CLX_WLAN_ERROR_WPS_SETUP_LOCKED									(CLX_WLAN_ERROR_BASE + 92)
#define CLX_WLAN_ERROR_WPS_DEVICE_PASSWORD_AUTHENTICATION_FAILED		(CLX_WLAN_ERROR_BASE + 93)
#define CLX_WLAN_ERROR_WPS_REGISTRAR_ALREADY_ACTIVE						(CLX_WLAN_ERROR_BASE + 94)
#define CLX_WLAN_ERROR_WPS_REGISTRAR_NOT_ACTIVE							(CLX_WLAN_ERROR_BASE + 95)
#define CLX_WLAN_ERROR_WPS_REGISTRAR_SETUP_LOCKED						(CLX_WLAN_ERROR_BASE + 96)
#define CLX_WLAN_ERROR_WPS_REGISTRAR_METHOD_NOT_SUPPORTED				(CLX_WLAN_ERROR_BASE + 97)
#define CLX_WLAN_ERROR_P2P_NO_PENDING_CONNECTION						(CLX_WLAN_ERROR_BASE + 98)
#define CLX_WLAN_ERROR_P2P_CONNECTION_CANCELLED							(CLX_WLAN_ERROR_BASE + 99)
#define CLX_WLAN_ERROR_LINK_LOST										(CLX_WLAN_ERROR_BASE + 100)
#define CLX_WLAN_ERROR_ROAMING_ATTEMPT_FAILED							(CLX_WLAN_ERROR_BASE + 101)
#define CLX_WLAN_ERROR_LINK_NOT_EXIST									(CLX_WLAN_ERROR_BASE + 102)
#define CLX_WLAN_ERROR_KEY_INDEX_NOT_SUPPORTED							(CLX_WLAN_ERROR_BASE + 103)
#define CLX_WLAN_ERROR_KEY_NOT_EXIST									(CLX_WLAN_ERROR_BASE + 104)
#define CLX_WLAN_ERROR_STACK_NOT_INITIALIZED							(CLX_WLAN_ERROR_BASE + 105)
#define CLX_WLAN_ERROR_VENDOR_SPECIFIC_IE_NOT_SUPPORTED_BY_DRIVER		(CLX_WLAN_ERROR_BASE + 106)
#define CLX_WLAN_ERROR_HW_COMMAND_COMPLETE_TIMEOUT			            (CLX_WLAN_ERROR_BASE + 107)
#define CLX_WLAN_ERROR_WPS_NOT_ENABLED		                            (CLX_WLAN_ERROR_BASE + 108)
#define CLX_WLAN_ERROR_BSS_NOT_REGISTERED_IN_EXTERNAL_SUPPLICANT		(CLX_WLAN_ERROR_BASE + 109)
#define CLX_WLAN_ERROR_MESH_NO_ROUTE_FOR_RX_PACKET						(CLX_WLAN_ERROR_BASE + 110)
#define CLX_WLAN_ERROR_PMF_CIPHER_NOT_SUPPORTED						    (CLX_WLAN_ERROR_BASE + 111)
#define CLX_WLAN_ERROR_PMF_POLICY_NOT_SUPPORTED						    (CLX_WLAN_ERROR_BASE + 112)
#define CLX_WLAN_ERROR_INVALID_GROUP_MANAGEMENT_CIPHER					(CLX_WLAN_ERROR_BASE + 113)
#define CLX_WLAN_ERROR_BAD_BG_SCAN_CONFIGURATION			            (CLX_WLAN_ERROR_BASE + 114)
#define CLX_WLAN_ERROR_BG_SCAN_TERMINATION_PENDING					    (CLX_WLAN_ERROR_BASE + 115)
#define CLX_WLAN_ERROR_BAD_USER_SCAN_CONFIGURATION			            (CLX_WLAN_ERROR_BASE + 116)
#define CLX_WLAN_ERROR_ROBUST_MANAGEMENT_POLICY_VIOLATION               (CLX_WLAN_ERROR_BASE + 117)
#define CLX_WLAN_ERROR_PRE_ASSOC_AUTHENTICATION_FAILED				    (CLX_WLAN_ERROR_BASE + 118)
#define CLX_WLAN_ERROR_INVALID_MAC_HEADER_FIELDS                        (CLX_WLAN_ERROR_BASE + 119)
#define CLX_WLAN_ERROR_FIRMWARE_ERROR                                   (CLX_WLAN_ERROR_BASE + 120)
#define CLX_WLAN_ERROR_BAD_AUTHENTICATION_FRAME                         (CLX_WLAN_ERROR_BASE + 121)
#define CLX_WLAN_ERROR_BAD_ASSOCIATION_REQUEST_FRAME                    (CLX_WLAN_ERROR_BASE + 122)
#define CLX_WLAN_ERROR_BAD_ASSOCIATION_RESPONSE_FRAME                   (CLX_WLAN_ERROR_BASE + 123)
#define CLX_WLAN_ERROR_ASSOCIATION_TIMEOUT					            (CLX_WLAN_ERROR_BASE + 124)
#define CLX_WLAN_ERROR_INTERFACE_PENDING_CONFIGURATION					(CLX_WLAN_ERROR_BASE + 125)
#define CLX_WLAN_ERROR_CONFIG_PARAM_NOT_INITIALIZED					    (CLX_WLAN_ERROR_BASE + 126)
#define CLX_WLAN_ERROR_INVALID_MESH_BSS_IE				                (CLX_WLAN_ERROR_BASE + 127)
#define CLX_WLAN_ERROR_MESH_TOO_MANY_REQUESTS_PENDING			        (CLX_WLAN_ERROR_BASE + 128)
#define CLX_WLAN_ERROR_MESH_NODE_NOT_RESPONSIVE		                    (CLX_WLAN_ERROR_BASE + 129)
#define CLX_WLAN_ERROR_CLARINOX_MESH_NOT_SUPPORTED	                    (CLX_WLAN_ERROR_BASE + 130)
#define CLX_WLAN_ERROR_BSS_IN_DIFFERENT_MESH_NETWORK	                (CLX_WLAN_ERROR_BASE + 131)
#define CLX_WLAN_ERROR_MESH_LOCAL_DOWNLINK_CLIENT_LEFT_BSS	            (CLX_WLAN_ERROR_BASE + 132)
#define CLX_WLAN_ERROR_MESH_NODE_NOT_ACCESSIBLE	                        (CLX_WLAN_ERROR_BASE + 133)
#define CLX_WLAN_ERROR_MESH_NODE_NOT_STARTED	                        (CLX_WLAN_ERROR_BASE + 134)
#define CLX_WLAN_ERROR_NON_MESH_NODE	                                (CLX_WLAN_ERROR_BASE + 135)


#define CLX_WLAN_STANDARD_IEEE80211_REASON_CODE		            		(CLX_WLAN_ERROR_BASE + 1000)
#define CLX_WLAN_LAST_STANDARD_IEEE80211_REASON_CODE		            (CLX_WLAN_ERROR_BASE + 1200)

#define CLX_WLAN_STANDARD_IEEE80211_STATUS_CODE		            		(CLX_WLAN_ERROR_BASE + 1201)
#define CLX_WLAN_LAST_STANDARD_IEEE80211_STATUS_CODE		            (CLX_WLAN_ERROR_BASE + 1400)

#define CLX_WLAN_ERROR_LAST											    (CLX_WLAN_LAST_STANDARD_IEEE80211_STATUS_CODE)


#endif  // WlanErrors_h

/******************************************************************************/
/* 1. MISRA C 2004 RULE VIOLATION:                                            */
/* Message       : Identifiers (internal and external) shall not rely on the  */
/*                 significance of more than 31 characters.                   */
/* Rule          : MISRA-C:2004 Rule 5.1                                      */
/* Justification : Improves clarity of macro definitions. The compiler used   */
/*                 supports symbols longer than 31 characters, hence no risks.*/
/******************************************************************************/


/******************************************************************************/ 
/* 1. MISRA C 2012 RULE VIOLATION:                                            */ 
/* Message       : A project should not contain unused macro declarations 	  */
/* Rule          : MISRA-C:2012 Rule 2.5                                      */ 
/* Justification : Macro declarations are available to be used in user		  */ 
/*				   applications.											  */
/******************************************************************************/

